### ISSUE TITLE
Few weird glitches

### ISSUE THREAD

**Issue by imreallyliam** [sodastereo/sofi-enhanced#1]
Overall - super happy! I always thought this was the biggest issue with SoFi's interface. There are a few bugs though.
![image](https://user-images.githubusercontent.com/18571399/177629014-f9400edc-f96d-4409-8754-5772a52ab2e5.png)

**Comment by sodastereo** [comment]
Glad to hear! Recently switched to SoFi and I couldn't get passed it. 

For the bug, what browser/version are you using?

**Comment by imreallyliam** [comment]
Chrome 103, though I assume you use Firefox as you linked the Firefox version of the Stylus extension

**Comment by sodastereo** [comment]
@imreallyliam for some reason I can't reproduce it on chrome. Can you please send me a screenshot of your Stylus editing area? Trying to see if the styles are not loading correctly. Do you happen to have any other styling apps enabled?
![Screen Shot 2022-07-06 at 12 59 58 PM](https://user-images.githubusercontent.com/65195487/177633940-8441bbe4-6409-438e-aea6-1e32f7c224f2.png)

**Comment by sodastereo** [comment]
Cannot reproduce
